services:
    db:
        image: postgres:latest
        container_name: quizly_database
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_USER: ${DB_USER}
            POSTGRES_PASSWORD: ${DB_PASSWORD}
        volumes:
            - postgres_data:/var/lib/postgresql

    web:
        build:
            context: .
            dockerfile: backend.Dockerfile
        image: quizly_backend:latest
        env_file: .env
        container_name: quizly_backend
        volumes:
            - .:/app
            - quizly_media:/app/media
            - quizly_static:/app/static
        ports:
            - "8000:8000"
        environment:
            - PYTHONUNBUFFERED=1
        depends_on:
            - db

volumes:
    postgres_data:
    quizly_media:
    quizly_static: